api_platform:
    version: 1.0.0
    defaults:
        enable_docs: true
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_maximum_items_per_page: 20
        pagination_items_per_page: 20
        pagination_client_items_per_page: true
        collection:
            pagination:
            items_per_page_parameter_name: itemsPerPage