controllers:
    resource:
        path: ../src/Presentation/Controller/
        namespace: App\Presentation\Controller
    type: attribute

token:
    path: /api/auth/login
    methods: [ "POST" ]
    