parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $apiUrl: '%env(API_URL)%'
            string $backendUrl: '%env(BACKEND_URL)%'
            string $env: '%env(APP_ENV)%'
            string $frontendUrl: '%env(FRONTEND_URL)%'
            string $uploadDirectory: '%kernel.project_dir%/public/uploads/'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Util/iterator_functions.php'

    app.event.authentication_success_listener:
        class: App\Infrastructure\Auth\Listener\AuthenticationSuccessListener
        tags:
            - {
                  name: kernel.event_listener,
                  event: lexik_jwt_authentication.on_authentication_success,
                  method: onAuthenticationSuccessResponse,
              }
    
    app.event.jwt_created_listener:
        class: App\Infrastructure\Auth\Listener\JWTCreatedListener
        tags:
            - {
                  name: kernel.event_listener,
                  event: lexik_jwt_authentication.on_jwt_created,
                  method: onJWTCreated,
              }

    App\Shared\Infrastructure\Fixture\AliceProvider:
        tags:
            - { name: nelmio_alice.faker.provider }
    
    App\Infrastructure\Serializer\CollectionNormalizer:
        tags:
            - { name: 'serializer.normalizer', priority: 64 }